import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import SidebarMain from "@/components/navigation/main/sidebar";
import { cn } from "@/lib/utils";
import NavMain from "@/components/navigation/main/nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body className={`${poppins.variable} antialiased `}>
        <div className="flex min-h-screen">
          <SidebarMain />
          <div className="flex-1 flex flex-col">
            <NavMain />
            <main className="p-4 flex-1 bg-slate-100">
              {children} {/* Konten halaman dashboard akan masuk ke sini */}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
