import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import SidebarMain from "@/components/navigation/sidebar-main";
import { cn } from "@/lib/utils";
import NavMain from "@/components/navigation/nav-main";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body className={`${poppins.variable} antialiased`}>
        <main className="flex flex-row">
          <SidebarMain />
          <div className="flex-1 flex flex-col">
            <NavMain />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
